### PR TITLE
Initial support for VS2022

### PR DESCRIPTION
**Pull request by timheuer**
Primarily a PR for #47 but takes it a bit further with a little code style cleanup, separating to have a version for VS2019 and VS2022, using GitHub Actions for a build/artifacts.

### CODE REVIEW

**Comment by kaleb-iskandar** [comment]
@timheuer I tried your build https://github.com/timheuer/NgrokExtensions/actions/runs/1695368100
after installed on my VS 2022 Community Edition, this popup show up, 
image
when I choose yes, this error show up, would be good if you can fix it and include it in your PR. Thanks
image

**Comment by timheuer** [comment]
@kaleb-iskandar looks like ngrok changed their download page a bit.  I'll have to take a look, but may take a bit with other things I need to get done.

**Comment by timheuer** [comment]
Ok, @kaleb-iskandar I worked around this quickly: https://github.com/timheuer/NgrokExtensions/actions/runs/1946282256

**Comment by kaleb-iskandar** [comment]
> Ok, @kaleb-iskandar I worked around this quickly: https://github.com/timheuer/NgrokExtensions/actions/runs/1946282256

@timheuer now it works, Thankyou.

**Comment by henda79** [comment]
Hey guys, I run in to this issue on VS2022 Enterprise.

image

Any thoughts ?

**Comment by timheuer** [comment]
> Hey guys, I run in to this issue on VS2022 Enterprise.
> 

Constantly hit this? Has it ever worked?

**Comment by henda79** [comment]
Its the first time I'd ever used it on VS2022, I use VS2019 without any issues there, but was working on a .NET 6 project and needed 2022. Built the package and installed. Tried few times with admin elevation then just gave up.

**Comment by timheuer** [comment]
@henda79 I just tried mine again and can't get this error, everything works for me.  Unfortunately this error is coming from the basic 'uncaught' exception handler to also not helpful, but basically it is coming from ngrok.exe itself.  If you tried the command-line itself I wonder if you're able to get it working.

**Comment by Swimburger** [comment]
I noticed that there's a duplicate folder _NgrokExt.Shared_ vs _NgrokExtensions.Shared_.
I'm assuming this a copy/paste and accidental git check in :)

**Comment by timheuer** [comment]
@Swimburger that could have been an oversight on my part for sure!  Only need one shared :-)

**Comment by Swimburger** [comment]
@timheuer What do we need for this PR to leave draft stage?

**Comment by timheuer** [comment]
> @timheuer What do we need for this PR to leave draft stage?

Honestly nothing :-) -- I kept it in draft because I know the repo is in a specific state with looking for assistance/maintainer.  I got the impression that a merge might be unlikely...but I'll submit it :-)

**Comment by Swimburger** [comment]
I was able to build the project and install it. I definitely encountered some bugs, but I also see those listed as existing issues, so they seem pre-existing. 

I was able to manually test this:
- As admin, ngrok installed
- ngrok started the tunnel at the right localhost address for ASP.NET and ASP.NET Core
- ngrok chose the correct domain when configured in web.config or appsettings.json for ASP.NET and ASP.NET Core

**Review by Swimburger — APPROVED** [review]

**Comment by timheuer** [comment]
> Quick question, are Shared projects the preferred way of code sharing for VS Extensions, or is there another reason Shared projects is preferred over a class library? I don't see shared projects often :)

I think either or are fine actually.  Shared projects don't seem to be working the same way with VSIX project types as they are with others (e.g., you can do a project-to-project reference in a classlib to a shared project as an example and it kind of acts as a source-level classlib ref and compiled into the main lib though (you can see this in a Blasor Wasm app when asp-hosted in the template).

Recalling when I did this I think I expected the shared projects to work and when they didn't just used linked files...tl;dr -- I got lazy.  A classlib with a ref should work :-)

**Comment by Swimburger** [comment]
Look at the VS2022 upgrade guidance, they seem to recommend Shared projects too: https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

LGTM!

**Comment by Swimburger** [comment]
Extension published at https://marketplace.visualstudio.com/items?itemName=DavidProthero.ngrokextensions-2022

**Comment by timheuer** [comment]
> Extension published at [marketplace.visualstudio.com/items?itemName=DavidProthero.ngrokextensions-2022](https://marketplace.visualstudio.com/items?itemName=DavidProthero.ngrokextensions-2022)

Awesome! Thanks @Swimburger for carrying the mantle and getting it done!

**Comment by Swimburger** [comment]
Thank you for the PR!!!

**Pull request merged**
